/* 
Script para inserção de dados em todas as tabelas para testes.
*/

DELETE FROM produto_produtor;
DELETE FROM produto;
DELETE FROM produtor;
DELETE FROM pontuacao_premiacao;
DELETE FROM premiacao;
DELETE FROM pontuacao;
DELETE FROM categoria;

ALTER SEQUENCE categoria_id_seq RESTART WITH 1;
ALTER SEQUENCE pontuacao_id_seq RESTART WITH 1;
ALTER SEQUENCE premiacao_id_seq RESTART WITH 1;
ALTER SEQUENCE produto_id_seq RESTART WITH 1;
ALTER SEQUENCE produtor_id_seq RESTART WITH 1;

INSERT INTO categoria (nome) VALUES ('A');
INSERT INTO categoria (nome) VALUES ('B');
INSERT INTO categoria (nome) VALUES ('C');

INSERT INTO pontuacao (categoria, colocacao, pontos) VALUES (1, 'H', 30);
INSERT INTO pontuacao (categoria, colocacao, pontos) VALUES (1, '1', 18);
INSERT INTO pontuacao (categoria, colocacao, pontos) VALUES (1, '2', 15);
INSERT INTO pontuacao (categoria, colocacao, pontos) VALUES (1, '3', 12);
INSERT INTO pontuacao (categoria, colocacao, pontos) VALUES (1, '4', 9);
INSERT INTO pontuacao (categoria, colocacao, pontos) VALUES (1, '5', 6);
INSERT INTO pontuacao (categoria, colocacao, pontos) VALUES (1, 'M', 3);
INSERT INTO pontuacao (categoria, colocacao, pontos) VALUES (2, 'H', 20);
INSERT INTO pontuacao (categoria, colocacao, pontos) VALUES (2, '1', 12);
INSERT INTO pontuacao (categoria, colocacao, pontos) VALUES (2, '2', 10);
INSERT INTO pontuacao (categoria, colocacao, pontos) VALUES (2, '3', 8);
INSERT INTO pontuacao (categoria, colocacao, pontos) VALUES (2, '4', 6);
INSERT INTO pontuacao (categoria, colocacao, pontos) VALUES (2, '5', 4);
INSERT INTO pontuacao (categoria, colocacao, pontos) VALUES (2, 'M', 2);
INSERT INTO pontuacao (categoria, colocacao, pontos) VALUES (3, 'H', 10);
INSERT INTO pontuacao (categoria, colocacao, pontos) VALUES (3, '1', 6);
INSERT INTO pontuacao (categoria, colocacao, pontos) VALUES (3, '2', 5);
INSERT INTO pontuacao (categoria, colocacao, pontos) VALUES (3, '3', 4);
INSERT INTO pontuacao (categoria, colocacao, pontos) VALUES (3, '4', 3);
INSERT INTO pontuacao (categoria, colocacao, pontos) VALUES (3, '5', 2);
INSERT INTO pontuacao (categoria, colocacao, pontos) VALUES (3, 'M', 1);

INSERT INTO premiacao (premio) VALUES ('Açúcar - 5 kg');
INSERT INTO premiacao (premio) VALUES ('Amaciante');
INSERT INTO premiacao (premio) VALUES ('Arroz - 1 kg');
INSERT INTO premiacao (premio) VALUES ('Bombril');
INSERT INTO premiacao (premio) VALUES ('Detergente');
INSERT INTO premiacao (premio) VALUES ('Extrato de tomate');
INSERT INTO premiacao (premio) VALUES ('Farinha - 5 kg');
INSERT INTO premiacao (premio) VALUES ('Farinha - 1 kg');
INSERT INTO premiacao (premio) VALUES ('Lamen');
INSERT INTO premiacao (premio) VALUES ('Leite condensado');
INSERT INTO premiacao (premio) VALUES ('Macarrão');
INSERT INTO premiacao (premio) VALUES ('Óleo de soja');
INSERT INTO premiacao (premio) VALUES ('Sabão em pedra');
INSERT INTO premiacao (premio) VALUES ('Sabão em pó');
INSERT INTO premiacao (premio) VALUES ('Sal');
INSERT INTO premiacao (premio) VALUES ('Sardinha');

INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (5, 1, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (2, 2, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (3, 2, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (4, 2, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (5, 2, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (2, 3, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (7, 3, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (3, 4, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (4, 4, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (5, 4, 2);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (7, 4, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (7, 5, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (3, 6, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (4, 6, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (5, 6, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (2, 7, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (3, 7, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (4, 7, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (2, 8, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (3, 8, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (4, 8, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (6, 8, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (5, 9, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (6, 9, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (6, 10, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (2, 11, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (4, 11, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (7, 11, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (2, 12, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (3, 12, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (4, 12, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (5, 12, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (6, 12, 2);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (7, 12, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (6, 13, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (2, 14, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (3, 14, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (5, 15, 1);
INSERT INTO pontuacao_premiacao (pontuacao, premiacao, quantidade) VALUES (6, 16, 1);

INSERT INTO produtor (nome, endereco) VALUES ('Produtor 1', 'Endereço 1');
INSERT INTO produtor (nome, endereco) VALUES ('Produtor 2', 'Endereço 2');
INSERT INTO produtor (nome, endereco) VALUES ('Produtor 3', 'Endereço 3');
INSERT INTO produtor (nome, endereco) VALUES ('Produtor 4', 'Endereço 4');
INSERT INTO produtor (nome, endereco) VALUES ('Produtor 5', 'Endereço 5');
INSERT INTO produtor (nome, endereco) VALUES ('Produtor 6', 'Endereço 6');
INSERT INTO produtor (nome, endereco) VALUES ('Produtor 7', 'Endereço 7');
INSERT INTO produtor (nome, endereco) VALUES ('Produtor 8', 'Endereço 8');
INSERT INTO produtor (nome, endereco) VALUES ('Produtor 9', 'Endereço 9');
INSERT INTO produtor (nome, endereco) VALUES ('Produtor 10', 'Endereço 10');
INSERT INTO produtor (nome, endereco) VALUES ('Produtor 11', 'Endereço 11');

INSERT INTO produto (nome, categoria) VALUES ('Atemóia', 1);
INSERT INTO produto (nome, categoria) VALUES ('Caqui Fuyu', 1);
INSERT INTO produto (nome, categoria) VALUES ('Coco', 1);
INSERT INTO produto (nome, categoria) VALUES ('Pecã', 1);
INSERT INTO produto (nome, categoria) VALUES ('Soja (grão)', 1);
INSERT INTO produto (nome, categoria) VALUES ('Espinafre (Horenso)', 2);
INSERT INTO produto (nome, categoria) VALUES ('Limão Taiti', 2);
INSERT INTO produto (nome, categoria) VALUES ('Poncã', 2);
INSERT INTO produto (nome, categoria) VALUES ('Tangerina', 2);
INSERT INTO produto (nome, categoria) VALUES ('Limão Rosa', 3);
INSERT INTO produto (nome, categoria) VALUES ('Milho (planta)', 3);
INSERT INTO produto (nome, categoria) VALUES ('Soja (planta)', 3);

INSERT INTO produto_produtor (produto, produtor, classificacao) VALUES (10, 1, NULL);
INSERT INTO produto_produtor (produto, produtor, classificacao) VALUES (5, 2, NULL);
INSERT INTO produto_produtor (produto, produtor, classificacao) VALUES (12, 2, NULL);
INSERT INTO produto_produtor (produto, produtor, classificacao) VALUES (5, 3, NULL);
INSERT INTO produto_produtor (produto, produtor, classificacao) VALUES (7, 3, NULL);
INSERT INTO produto_produtor (produto, produtor, classificacao) VALUES (8, 3, NULL);
INSERT INTO produto_produtor (produto, produtor, classificacao) VALUES (12, 3,'1');
INSERT INTO produto_produtor (produto, produtor, classificacao) VALUES (5, 4, NULL);
INSERT INTO produto_produtor (produto, produtor, classificacao) VALUES (4, 4, '2');
INSERT INTO produto_produtor (produto, produtor, classificacao) VALUES (8, 4, 'M');
INSERT INTO produto_produtor (produto, produtor, classificacao) VALUES (12, 4, NULL);
INSERT INTO produto_produtor (produto, produtor, classificacao) VALUES (1, 5, '3');
INSERT INTO produto_produtor (produto, produtor, classificacao) VALUES (2, 5, 'M');
INSERT INTO produto_produtor (produto, produtor, classificacao) VALUES (3, 5, '1');
INSERT INTO produto_produtor (produto, produtor, classificacao) VALUES (4, 5, NULL);
INSERT INTO produto_produtor (produto, produtor, classificacao) VALUES (7, 5, NULL);
INSERT INTO produto_produtor (produto, produtor, classificacao) VALUES (8, 5, NULL);
INSERT INTO produto_produtor (produto, produtor, classificacao) VALUES (9, 5, NULL);
INSERT INTO produto_produtor (produto, produtor, classificacao) VALUES (10, 5, 'M');
INSERT INTO produto_produtor (produto, produtor, classificacao) VALUES (11, 5, NULL);
INSERT INTO produto_produtor (produto, produtor, classificacao) VALUES (12, 5, NULL);